### ISSUE TITLE
Docker image tag

### ISSUE THREAD

**Issue by nervo** [mkilchhofer/logrotate-container#2]
Hi, any chance to add tags to your docker image ?
I don't feel very comfortable using `latest` :)

**Comment by mkilchhofer** [comment]
Hi @nervo 
See referenced PR #3. Is this suitable for you?

The idea was:
1. rebuild the Dockerfile weekly against latest Alpine Linux base image
2. master branch builds `:latest`, `:<logroate major>`, `:<logroate major>.<logroate minor>` and a pinned version (non overwriting): `:<logroate full version>-build<travis build number`.
  --> at the moment we would have:
    - `latest`
    - `3`
    - `3.10`
    - `3.10.0-build16`

**Comment by nervo** [comment]
@mkilchhofer yep, that's a good start !
From my own point of view, you also need to:
- allow idempotency by setting an alpine version (not `latest`
- don't run as user 1000, it generates error on logrotate side (rc 1), and log files are often own by system users such as www-data

**Comment by mkilchhofer** [comment]
> * allow idempotency by setting an alpine version (not `latest`

What I do not want is to manually update this repository every time, alpine releases a new patch version (eg. 3.10.x -> 3.10.y). I then prefer usage like `FROM alpine:3` or `FROM alpine:3.10`.

> * don't run as user 1000, it generates error on logrotate side (rc 1), and log files are often own by system users such as www-data
The idea behind user 1000 is to allow this also on my employers openshift setup, where root processes inside a container are not allowed. But yes, they then could define a kubernetes security context for this like:
```
...
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
...
```
Even you should be able to run it as root by providing `runAsUser: 0` and `runAsGroup: 0`.

**Comment by nervo** [comment]
yep, :+1: for `FROM alpine:3.10` you're right.
I sure can define securityContext,but let's face reality: a lot of docker images run as root :)

**Comment by mkilchhofer** [comment]
ACK, for both 2 points :)
I change the Dockerfile to `FROM alpine:3.10` and remove the `USER 1000` line. If someone wants to run it as non-root, they have to specify a securityContext or fork the repo ^^.
